REVOKE UPDATE (redacted_at, state_before, state_after, metadata, ip, user_agent) ON audit_entries FROM cypra_runtime;
REVOKE SELECT, INSERT ON audit_entries FROM cypra_runtime;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM cypra_runtime;
REVOKE USAGE ON SCHEMA public FROM cypra_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM cypra_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM cypra_migrate;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM cypra_migrate;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM cypra_migrate;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM cypra_migrate;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM cypra_migrate;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM cypra_migrate;
REVOKE USAGE, CREATE ON SCHEMA public FROM cypra_migrate;

DROP ROLE IF EXISTS cypra_runtime;
DROP ROLE IF EXISTS cypra_migrate;
