version: "3"

tasks:
  dev:
    cmds:
      - make dev
  build:
    cmds:
      - make build
  test:
    cmds:
      - make test
  lint:
    cmds:
      - make lint
  typecheck:
    cmds:
      - make typecheck
  ci:
    cmds:
      - make ci
  ci-pipeline:
    cmds:
      - make ci-pipeline
  image-size:
    cmds:
      - make image-size
